export const sampleCities = [
    {
      coords: {
        "X13_Y12": { x: 13, y: 12, type: "road" },
        "X13_Y11": { x: 13, y: 11, type: "road" },
        "X13_Y10": { x: 13, y: 10, type: "road" },
        "X13_Y9": { x: 13, y: 9, type: "road" },
        "X13_Y8": { x: 13, y: 8, type: "road" },
        "X13_Y7": { x: 13, y: 7, type: "road" },
        "X13_Y6": { x: 13, y: 6, type: "road" },
        "X13_Y5": { x: 13, y: 5, type: "road" },
        "X13_Y4": { x: 13, y: 4, type: "road" },
        "X12_Y4": { x: 12, y: 4, type: "road" },
        "X11_Y4": { x: 11, y: 4, type: "road" },
        "X10_Y4": { x: 10, y: 4, type: "road" },
        "X9_Y4": { x: 9, y: 4, type: "road" },
        "X8_Y4": { x: 8, y: 4, type: "road" },
        "X7_Y4": { x: 7, y: 4, type: "road" },
        "X6_Y4": { x: 6, y: 4, type: "road" },
        "X5_Y4": { x: 5, y: 4, type: "road" },
        "X4_Y4": { x: 4, y: 4, type: "road" },
        "X3_Y4": { x: 3, y: 4, type: "road" },
        "X3_Y5": { x: 3, y: 5, type: "road" },
        "X3_Y6": { x: 3, y: 6, type: "road" },
        "X3_Y7": { x: 3, y: 7, type: "road" },
        "X3_Y8": { x: 3, y: 8, type: "road" },
        "X3_Y9": { x: 3, y: 9, type: "road" },
        "X3_Y10": { x: 3, y: 10, type: "road" },
        "X3_Y11": { x: 3, y: 11, type: "road" },
        "X3_Y12": { x: 3, y: 12, type: "road" },
        "X12_Y12": { x: 12, y: 12, type: "road" },
        "X11_Y12": { x: 11, y: 12, type: "road" },
        "X10_Y12": { x: 10, y: 12, type: "road" },
        "X9_Y12": { x: 9, y: 12, type: "road" },
        "X8_Y12": { x: 8, y: 12, type: "road" },
        "X7_Y12": { x: 7, y: 12, type: "road" },
        "X6_Y12": { x: 6, y: 12, type: "road" },
        "X5_Y12": { x: 5, y: 12, type: "road" },
        "X4_Y12": { x: 4, y: 12, type: "road" },
        "X8_Y11": { x: 8, y: 11, type: "road" },
        "X8_Y10": { x: 8, y: 10, type: "road" },
        "X8_Y9": { x: 8, y: 9, type: "road" },
        "X8_Y8": { x: 8, y: 8, type: "road" },
        "X8_Y7": { x: 8, y: 7, type: "road" },
        "X8_Y6": { x: 8, y: 6, type: "road" },
        "X8_Y5": { x: 8, y: 5, type: "road" },
        "X12_Y8": { x: 12, y: 8, type: "road" },
        "X11_Y8": { x: 11, y: 8, type: "road" },
        "X10_Y8": { x: 10, y: 8, type: "road" },
        "X9_Y8": { x: 9, y: 8, type: "road" },
        "X7_Y9": { x: 7, y: 9, type: "road" },
        "X6_Y9": { x: 6, y: 9, type: "road" },
        "X5_Y9": { x: 5, y: 9, type: "road" },
        "X4_Y9": { x: 4, y: 9, type: "road" },
        "X6_Y8": { x: 6, y: 8, type: "road" },
        "X6_Y7": { x: 6, y: 7, type: "road" },
        "X5_Y7": { x: 5, y: 7, type: "road" },
        "X5_Y6": { x: 5, y: 6, type: "road" },
        "X5_Y5": { x: 5, y: 5, type: "road" },
        "X12_Y5": { x: 12, y: 5, type: "residential" },
        "X11_Y5": { x: 11, y: 5, type: "powerPlant" },
        "X10_Y5": { x: 10, y: 5, type: "residential" },
        "X9_Y5": { x: 9, y: 5, type: "residential" },
        "X12_Y6": { x: 12, y: 6, type: "commercial" },
        "X2_Y11": { x: 2, y: 11, type: "powerLine" },
        "X12_Y7": { x: 12, y: 7, type: "commercial" },
        "X4_Y8": { x: 4, y: 8, type: "industrial" },
        "X4_Y7": { x: 4, y: 7, type: "industrial" },
        "X4_Y6": { x: 4, y: 6, type: "industrial" },
        "X4_Y5": { x: 4, y: 5, type: "industrial" },
        "X5_Y8": { x: 5, y: 8, type: "commercial" },
        "X9_Y7": { x: 9, y: 7, type: "bank" },
        "X10_Y7": { x: 10, y: 7, type: "hospital" },
        "X7_Y5": { x: 7, y: 5, type: "mall" },
        "X14_Y4": { x: 14, y: 4, type: "powerPlant" },
        "X13_Y13": { x: 13, y: 13, type: "powerPlant" },
        "X2_Y3": { x: 2, y: 3, type: "powerPlant" },
        "X7_Y11": { x: 7, y: 11, type: "industrial" },
        "X6_Y11": { x: 6, y: 11, type: "industrial" },
        "X4_Y11": { x: 4, y: 11, type: "industrial" },
        "X4_Y10": { x: 4, y: 10, type: "industrial" },
        "X5_Y10": { x: 5, y: 10, type: "commercial" },
        "X12_Y11": { x: 12, y: 11, type: "residential" },
        "X12_Y10": { x: 12, y: 10, type: "residential" },
        "X9_Y13": { x: 9, y: 13, type: "stadium" },
        "X9_Y11": { x: 9, y: 11, type: "commercial" },
        "X9_Y10": { x: 9, y: 10, type: "commercial" },
        "X9_Y9": { x: 9, y: 9, type: "commercial" },
        "X2_Y12": { x: 2, y: 12, type: "powerPlant" },
        "X2_Y10": { x: 2, y: 10, type: "powerLine" },
        "X2_Y9": { x: 2, y: 9, type: "powerLine" },
        "X2_Y8": { x: 2, y: 8, type: "powerLine" },
        "X2_Y7": { x: 2, y: 7, type: "powerLine" },
        "X2_Y6": { x: 2, y: 6, type: "powerLine" },
        "X2_Y5": { x: 2, y: 5, type: "powerLine" },
        "X2_Y4": { x: 2, y: 4, type: "powerLine" }
      },
      camera: {
        camAzimuth: 225,
        camElevation: 45,
        camRadius: 0.3,
        camOrigin: { x: 8, y: 0, "z": 8 }
      },
      ui: {
        selectType: "select",
        selModel: "modelA",
        selectedCmdId: "uiMgr-BtnSelect",
        bPaused: false,
        fileName: "A형 모델"
      }
    },
    {
      coords: {
        "X13_Y13": { x: 13, y: 13, type: "road" },
        "X12_Y13": { x: 12, y: 13, type: "road" },
        "X11_Y13": { x: 11, y: 13, type: "road" },
        "X10_Y13": { x: 10, y: 13, type: "road" },
        "X9_Y13": { x: 9, y: 13, type: "road" },
        "X8_Y13": { x: 8, y: 13, type: "road" },
        "X7_Y13": { x: 7, y: 13, type: "road" },
        "X6_Y13": { x: 6, y: 13, type: "road" },
        "X6_Y12": { x: 6, y: 12, type: "road" },
        "X6_Y11": { x: 6, y: 11, type: "road" },
        "X6_Y10": { x: 6, y: 10, type: "road" },
        "X6_Y9": { x: 6, y: 9, type: "road" },
        "X6_Y8": { x: 6, y: 8, type: "road" },
        "X7_Y8": { x: 7, y: 8, type: "road" },
        "X8_Y8": { x: 8, y: 8, type: "road" },
        "X9_Y8": { x: 9, y: 8, type: "road" },
        "X10_Y8": { x: 10, y: 8, type: "road" },
        "X11_Y8": { x: 11, y: 8, type: "road" },
        "X12_Y8": { x: 12, y: 8, type: "road" },
        "X13_Y8": { x: 13, y: 8, type: "road" },
        "X13_Y9": { x: 13, y: 9, type: "road" },
        "X13_Y10": { x: 13, y: 10, type: "road" },
        "X13_Y11": { x: 13, y: 11, type: "road" },
        "X13_Y12": { x: 13, y: 12, type: "road" },
        "X7_Y6": { x: 7, y: 6, type: "road" },
        "X6_Y6": { x: 6, y: 6, type: "road" },
        "X5_Y6": { x: 5, y: 6, type: "road" },
        "X4_Y6": { x: 4, y: 6, type: "road" },
        "X3_Y6": { x: 3, y: 6, type: "road" },
        "X2_Y6": { x: 2, y: 6, type: "road" },
        "X2_Y5": { x: 2, y: 5, type: "road" },
        "X2_Y4": { x: 2, y: 4, type: "road" },
        "X2_Y3": { x: 2, y: 3, type: "road" },
        "X2_Y2": { x: 2, y: 2, type: "road" },
        "X3_Y2": { x: 3, y: 2, type: "road" },
        "X4_Y2": { x: 4, y: 2, type: "road" },
        "X5_Y2": { x: 5, y: 2, type: "road" },
        "X6_Y2": { x: 6, y: 2, type: "road" },
        "X7_Y2": { x: 7, y: 2, type: "road" },
        "X8_Y2": { x: 8, y: 2, type: "road" },
        "X9_Y2": { x: 9, y: 2, type: "road" },
        "X10_Y2": { x: 10, y: 2, type: "road" },
        "X11_Y2": { x: 11, y: 2, type: "road" },
        "X12_Y2": { x: 12, y: 2, type: "road" },
        "X12_Y3": { x: 12, y: 3, type: "road" },
        "X12_Y4": { x: 12, y: 4, type: "road" },
        "X12_Y5": { x: 12, y: 5, type: "road" },
        "X12_Y6": { x: 12, y: 6, type: "road" },
        "X11_Y6": { x: 11, y: 6, type: "road" },
        "X10_Y6": { x: 10, y: 6, type: "road" },
        "X9_Y6": { x: 9, y: 6, type: "road" },
        "X8_Y6": { x: 8, y: 6, type: "road" },
        "X8_Y7": { x: 8, y: 7, type: "road" },
        "X11_Y7": { x: 11, y: 7, type: "road" },
        "X8_Y5": { x: 8, y: 5, type: "road" },
        "X8_Y4": { x: 8, y: 4, type: "road" },
        "X8_Y3": { x: 8, y: 3, type: "road" },
        "X5_Y5": { x: 5, y: 5, type: "road" },
        "X5_Y4": { x: 5, y: 4, type: "road" },
        "X6_Y4": { x: 6, y: 4, type: "road" },
        "X6_Y3": { x: 6, y: 3, type: "road" },
        "X11_Y4": { x: 11, y: 4, type: "road" },
        "X10_Y4": { x: 10, y: 4, type: "road" },
        "X9_Y4": { x: 9, y: 4, type: "road" },
        "X10_Y12": { x: 10, y: 12, type: "road" },
        "X10_Y11": { x: 10, y: 11, type: "road" },
        "X10_Y10": { x: 10, y: 10, type: "road" },
        "X10_Y9": { x: 10, y: 9, type: "road" },
        "X9_Y12": { x: 9, y: 12, type: "residential" },
        "X8_Y12": { x: 8, y: 12, type: "industrial" },
        "X7_Y12": { x: 7, y: 12, type: "residential" },
        "X12_Y9": { x: 12, y: 9, type: "residential" },
        "X11_Y9": { x: 11, y: 9, type: "residential" },
        "X3_Y5": { x: 3, y: 5, type: "residential" },
        "X3_Y4": { x: 3, y: 4, type: "residential" },
        "X3_Y3": { x: 3, y: 3, type: "residential" },
        "X14_Y13": { x: 14, y: 13, type: "powerPlant" },
        "X7_Y9": { x: 7, y: 9, type: "powerPlant" },
        "X11_Y3": { x: 11, y: 3, type: "industrial" },
        "X10_Y3": { x: 10, y: 3, type: "industrial" },
        "X9_Y3": { x: 9, y: 3, type: "industrial" },
        "X11_Y5": { x: 11, y: 5, type: "commercial" },
        "X5_Y3": { x: 5, y: 3, type: "commercial" },
        "X7_Y5": { x: 7, y: 5, type: "industrial" },
        "X7_Y4": { x: 7, y: 4, type: "industrial" },
        "X7_Y3": { x: 7, y: 3, type: "industrial" },
        "X9_Y9": { x: 9, y: 9, type: "bank" },
        "X9_Y5": { x: 9, y: 5, type: "trainstation" },
        "X12_Y12": { x: 12, y: 12, type: "school" },
        "X12_Y11": { x: 12, y: 11, type: "post" },
        "X7_Y11": { x: 7, y: 11, type: "museum" },
        "X10_Y7": { x: 10, y: 7, type: "museum" },
        "X9_Y7": { x: 9, y: 7, type: "mall" },
        "X3_Y7": { x: 3, y: 7, type: "powerPlant" },
        "X5_Y13": { x: 5, y: 13, type: "powerPlant" },
        "X13_Y2": { x: 13, y: 2, type: "powerPlant" }
      },
      camera: {
        camAzimuth: 225,
        camElevation: 45,
        camRadius: 0.3,
        camOrigin: { x: 8, y: 0, "z": 8 }
      },
      ui: {
        selectType: "select",
        selModel: "modelB",
        selectedCmdId: "uiMgr-BtnSelect",
        bPaused: false,
        fileName: "B형 모델"
      }
    },
    {
      coords: {
        "X13_Y7": { x: 13, y: 7, type: "road" },
        "X12_Y6": { x: 12, y: 6, type: "road" },
        "X12_Y5": { x: 12, y: 5, type: "road" },
        "X11_Y5": { x: 11, y: 5, type: "road" },
        "X11_Y4": { x: 11, y: 4, type: "road" },
        "X10_Y4": { x: 10, y: 4, type: "road" },
        "X13_Y6": { x: 13, y: 6, type: "road" },
        "X13_Y8": { x: 13, y: 8, type: "road" },
        "X13_Y9": { x: 13, y: 9, type: "road" },
        "X13_Y10": { x: 13, y: 10, type: "road" },
        "X13_Y11": { x: 13, y: 11, type: "road" },
        "X12_Y11": { x: 12, y: 11, type: "road" },
        "X11_Y11": { x: 11, y: 11, type: "road" },
        "X11_Y12": { x: 11, y: 12, type: "road" },
        "X10_Y12": { x: 10, y: 12, type: "road" },
        "X9_Y12": { x: 9, y: 12, type: "road" },
        "X8_Y12": { x: 8, y: 12, type: "road" },
        "X7_Y12": { x: 7, y: 12, type: "road" },
        "X6_Y12": { x: 6, y: 12, type: "road" },
        "X5_Y12": { x: 5, y: 12, type: "road" },
        "X5_Y11": { x: 5, y: 11, type: "road" },
        "X4_Y11": { x: 4, y: 11, type: "road" },
        "X4_Y10": { x: 4, y: 10, type: "road" },
        "X3_Y10": { x: 3, y: 10, type: "road" },
        "X3_Y9": { x: 3, y: 9, type: "road" },
        "X3_Y8": { x: 3, y: 8, type: "road" },
        "X3_Y7": { x: 3, y: 7, type: "road" },
        "X3_Y6": { x: 3, y: 6, type: "road" },
        "X3_Y4": { x: 3, y: 4, type: "road" },
        "X3_Y3": { x: 3, y: 3, type: "road" },
        "X3_Y2": { x: 3, y: 2, type: "road" },
        "X4_Y2": { x: 4, y: 2, type: "road" },
        "X5_Y2": { x: 5, y: 2, type: "road" },
        "X6_Y2": { x: 6, y: 2, type: "road" },
        "X8_Y2": { x: 8, y: 2, type: "road" },
        "X8_Y3": { x: 8, y: 3, type: "road" },
        "X9_Y3": { x: 9, y: 3, type: "road" },
        "X10_Y3": { x: 10, y: 3, type: "road" },
        "X7_Y2": { x: 7, y: 2, type: "road" },
        "X3_Y5": { x: 3, y: 5, type: "road" },
        "X2_Y7": { x: 2, y: 7, type: "road" },
        "X1_Y7": { x: 1, y: 7, type: "road" },
        "X9_Y13": { x: 9, y: 13, type: "road" },
        "X9_Y14": { x: 9, y: 14, type: "road" },
        "X12_Y12": { x: 12, y: 12, type: "road" },
        "X12_Y13": { x: 12, y: 13, type: "road" },
        "X12_Y14": { x: 12, y: 14, type: "road" },
        "X12_Y8": { x: 12, y: 8, type: "road" },
        "X10_Y8": { x: 10, y: 8, type: "road" },
        "X9_Y8": { x: 9, y: 8, type: "road" },
        "X11_Y8": { x: 11, y: 8, type: "road" },
        "X9_Y11": { x: 9, y: 11, type: "road" },
        "X9_Y9": { x: 9, y: 9, type: "road" },
        "X9_Y10": { x: 9, y: 10, type: "road" },
        "X8_Y8": { x: 8, y: 8, type: "road" },
        "X7_Y8": { x: 7, y: 8, type: "road" },
        "X6_Y8": { x: 6, y: 8, type: "road" },
        "X5_Y8": { x: 5, y: 8, type: "road" },
        "X5_Y7": { x: 5, y: 7, type: "road" },
        "X4_Y7": { x: 4, y: 7, type: "road" },
        "X8_Y7": { x: 8, y: 7, type: "road" },
        "X8_Y6": { x: 8, y: 6, type: "road" },
        "X8_Y5": { x: 8, y: 5, type: "road" },
        "X8_Y4": { x: 8, y: 4, type: "road" },
        "X7_Y5": { x: 7, y: 5, type: "road" },
        "X6_Y5": { x: 6, y: 5, type: "road" },
        "X5_Y5": { x: 5, y: 5, type: "road" },
        "X4_Y5": { x: 4, y: 5, type: "road" },
        "X12_Y7": { x: 12, y: 7, type: "residential" },
        "X11_Y7": { x: 11, y: 7, type: "residential" },
        "X10_Y7": { x: 10, y: 7, type: "commercial" },
        "X9_Y7": { x: 9, y: 7, type: "residential" },
        "X13_Y5": { x: 13, y: 5, type: "powerPlant" },
        "X4_Y12": { x: 4, y: 12, type: "powerPlant" },
        "X8_Y11": { x: 8, y: 11, type: "industrial" },
        "X7_Y11": { x: 7, y: 11, type: "industrial" },
        "X6_Y11": { x: 6, y: 11, type: "industrial" },
        "X10_Y11": { x: 10, y: 11, type: "industrial" },
        "X10_Y10": { x: 10, y: 10, type: "industrial" },
        "X10_Y9": { x: 10, y: 9, type: "industrial" },
        "X8_Y10": { x: 8, y: 10, type: "commercial" },
        "X8_Y9": { x: 8, y: 9, type: "commercial" },
        "X10_Y5": { x: 10, y: 5, type: "school" },
        "X12_Y9": { x: 12, y: 9, type: "bank" },
        "X9_Y4": { x: 9, y: 4, type: "residential" },
        "X9_Y6": { x: 9, y: 6, type: "policestation" },
        "X6_Y3": { x: 6, y: 3, type: "residential" },
        "X5_Y3": { x: 5, y: 3, type: "residential" },
        "X4_Y3": { x: 4, y: 3, type: "industrial" },
        "X7_Y3": { x: 7, y: 3, type: "commercial" },
        "X7_Y7": { x: 7, y: 7, type: "industrial" },
        "X6_Y7": { x: 6, y: 7, type: "industrial" },
        "X4_Y6": { x: 4, y: 6, type: "industrial" },
        "X5_Y6": { x: 5, y: 6, type: "industrial" },
        "X2_Y6": { x: 2, y: 6, type: "powerPlant" },
        "X13_Y12": { x: 13, y: 12, type: "powerPlant" },
        "X5_Y9": { x: 5, y: 9, type: "school" },
        "X4_Y9": { x: 4, y: 9, type: "industrial" },
        "X4_Y8": { x: 4, y: 8, type: "industrial" },
        "X5_Y4": { x: 5, y: 4, type: "school" },
        "X2_Y2": { x: 2, y: 2, type: "stadium" },
      },
      camera: {
        camAzimuth: 225,
        camElevation: 45,
        camRadius: 0.3,
        camOrigin: { x: 8, y: 0, "z": 8 }
      },
      ui: {
        selectType: "select",
        selModel: "modelC",
        selectedCmdId: "uiMgr-BtnSelect",
        bPaused: false,
        fileName: "C형 모델"
      }
    }
  ]